CREATE TABLE pings (
  id SERIAL PRIMARY KEY,
  service_id VARCHAR(255) NOT NULL,
  latency INTEGER NOT NULL,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
