-- Users Table
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Peers Table
CREATE TABLE peers (
  id VARCHAR(12) PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  url VARCHAR(255) NOT NULL,
  frequency INTEGER NOT NULL,
  timeout INTEGER NOT NULL,
  location VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Pings Table
CREATE TABLE pings (
  id SERIAL PRIMARY KEY,
  peer_id VARCHAR(12) NOT NULL REFERENCES peers(id),
  latency INTEGER NOT NULL,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
